version: '3'
services:

  db:
    image: mongo
    command: --port 28020
  web:
    image: mcr.microsoft.com/dotnet/core/sdk
    command: sh /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "5010:5005"
    depends_on:
      - db
