name: Build Client for Mobile

on: [push, pull_request, workflow_dispatch]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: src/Cynthia.Card.Unity/src/Cynthia.Unity.Card/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: src/Cynthia.Card.Unity/src/Cynthia.Unity.Card
          buildName: DiyGwent-${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: DiyGwent-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
